/*
  Auto-generated by Spline
*/
import { useEffect, useState } from 'react'

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'
import { Suspense } from 'react'
import { Canvas } from '@react-three/fiber'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/O78EjJj9jpJdSoeG/scene.splinecode')

  const [AxeX, setAxeX] = useState(0);
  const [AxeY, setAxeY] = useState(0);

  const logMouseposition = (e) => {
    setAxeX(e.clientX / window.innerWidth);
    setAxeY(e.clientY / window.innerHeight);
    /* console.log("Mouse event", e.clientX / window.innerWidth, e.clientY / window.innerHeight); */
  };

  useEffect(() => {
    /* console.log("useEffect() called"); */
    window.addEventListener('mousemove', logMouseposition);
    return () => {
      /* console.log("component unmounted"); */
      window.removeEventListener('mousemove', logMouseposition);
    };
  }, []);

  return (
    <>
        <Suspense fallback={null}>
            <Canvas shadows flat linear className='model'>
                <color attach="background" args={['#121316']} />
                <group {...props} dispose={null}>
                    <mesh
                        name="Sphere"
                        geometry={nodes.Sphere.geometry}
                        material={materials['Sphere Material']}
                        castShadow
                        receiveShadow
                        rotation={[AxeY, AxeX, 0]}
                        position={[-150, -50, 0]}
                    />
                    <OrthographicCamera
                        name="Default Camera"
                        makeDefault={true}
                        far={50000}
                        near={-50000}
                        position={[1.24, -19.24, 1000]}
                    >
                    <directionalLight
                        name="Default Directional Light"
                        intensity={0.75}
                        shadow-mapSize-width={1024}
                        shadow-mapSize-height={1024}
                        shadow-camera-near={1}
                        position={[850000, 1300000, 1000000]}
                    />
                    </OrthographicCamera>
                </group>
            </Canvas>
        </Suspense>
    </>
  )
}
